server:
  port: 8041
spring:
  application:
    name: order-service-sentinel
  cloud:
    nacos:
      server-addr: 192.168.149.128:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
        #ephemeral: true #设置永久实例(当前实例挂了,也不会删除实例)(false为永久实例)
#springboot默认的日志级别是info,feign的debug日志级别不会输出
#feign:
#  sentinel:
#    #openfeign整合sentinel
#    enabled: true
feign:
  sentinel:
    enabled: true

