server:
  port: 8040
spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.149.128:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public
        #ephemeral: true #设置永久实例(当前实例挂了,也不会删除实例)(false为永久实例)
#springboot默认的日志级别是info,feign的debug日志级别不会输出
logging:
  level:
   com.tuling.mall.feigndemo.feign: debug

feign:
  client:
    config:
      stock-service:
        loggerLevel: BASIC
        requestInterceptors[0]: #配置拦截器
          com.ouliang.order.intercptor.feign.CustomFeignInterceptor


